CREATE DATABASE hospivibe;
USE hospivibe;

-- creacio schemes
CREATE SCHEMA IF NOT EXISTS cantina;
CREATE SCHEMA IF NOT EXISTS pacient;
CREATE SCHEMA IF NOT EXISTS estructura;
CREATE SCHEMA IF NOT EXISTS dades_per;
CREATE SCHEMA IF NOT EXISTS seguretat;


